name: AtCoder Submits

on:
  schedule:
    - cron: '0 15 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: miyoshi-akira/atcoder-submits-action@v1
        with:
          atcoder_user_id: 'jon0920'
          github_token: ${{ secrets.APP_TOKEN }}
